# Generated by Django 5.0.6 on 2024-06-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0006_sale_saledetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='employee',
            new_name='user',
        ),
    ]
